language: java

# Set JDK needed for JavaTestApplication
jdk:
  - oraclejdk8    

 # Enable initializing of GUI context required for running tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: 
 - cd CodenameOne
 - ant jar
 - cd ../CodenameOneDesigner
 - ant release
